<a href="https://colab.research.google.com/github/paulinaplachno/data-science/blob/main/01_wprowadzenie_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Colab')

Hello Colab


In [3]:
import numpy as np


In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.random.randint(low=10, high=101, size=10)

array([11, 50, 80, 90, 10, 71, 57, 29, 93, 33])

In [ ]:
np.random.choice([4,2,1,3,5])

2

In [ ]:
np.random.randn(10, 4)

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [4]:
np.exp(1)

2.718281828459045

In [5]:
np.sqrt(9)

3.0

In [7]:
np.all([2, 3, 1])

True

In [8]:
np.any([1, 2, 3])

True

In [9]:
bool(0)

False

In [12]:
A = np.random.rand(5)
A

array([0.05446649, 0.87390085, 0.35029801, 0.96567543, 0.90270991])

In [13]:
np.argmax(A)

3

In [14]:
A[np.argmax(A)]

0.9656754298502238

In [15]:
np.argsort(A)

array([0, 2, 1, 4, 3])

In [16]:
np.max(A)

0.9656754298502238

In [17]:
np.median(A)

0.8739008459508862

In [18]:
A[2]

0.3502980092131487

In [19]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
A[2]

2

In [21]:
A[2: ]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
A[:2]

array([0, 1])

In [23]:
A[[0,2]]

array([0, 2])

In [24]:
for row in A:
  print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [25]:
A.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A


array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [27]:
A> 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [28]:
A[ A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [30]:
A[np.bitwise_and(A> -5, A <5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [31]:
A[np.bitwise_or(A <-5, A >5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])